### ISSUE TITLE
`onCancel` handlers should be called immediately if the promise was cancelled already

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/p-cancelable#15]

**Comment by sindresorhus** [comment]
What do you mean by "cancelled already"? Can you provide an example of what's not working as expected? 

The `onCancel` handlers are called synchronously when use call `.cancel()`: https://github.com/sindresorhus/p-cancelable/blob/354c4000c3b7602faa601e7e060a05d581b89419/index.js#L72-L85

**Comment by szmarczak** [comment]
Sorry, here's the example:

```js
const PCancelable = require('p-cancelable');
const cancelable = new PCancelable((resolve, reject, onCancel) => {
	setTimeout(() => {
        console.log('Timeout');
		onCancel(() => console.log('Cancelled')); // Should this be called?
	}, 1000);
});

cancelable.catch(() => {});
cancelable.cancel();
```

**Comment by Spy-Seth** [comment]
Hi @szmarczak, you are defining the `onCancel` in the setTimeout, so when you do `cancelable.cancel();` it is not yet executed. Move the call outside the setTimeout to make it works:

```js

const PCancelable = require('p-cancelable');
const cancelable = new PCancelable((resolve, reject, onCancel) => {
	onCancel(() => console.log('Cancelled')); // It will be called

	setTimeout(() => {
        	console.log('Timeout');
	}, 1000);
});

cancelable.catch(() => {});
cancelable.cancel();
```

**Comment by szmarczak** [comment]
@Spy-Seth IKR. This is not what I want. What I am trying to show, is that if onCancel callback should be called if the promise was cancelled already.

**Comment by bfred-it** [comment]
It took a bit to understand this too.

This is akin to adding an event listener after the event was fired, e.g.

```js
document.click();
document.addEventListener('click', console.log);
```

Now in `p-cancelable` terms:

```js
p.cancel();
...
onCancel(console.log);
```

I think this could be achieved by treating `onCancel` callbacks as `.then` callbacks of a private Promise, instead of manually creating an array (`_cancelHandlers`) and calling them with a loop.

**Comment by bfred-it** [comment]
However, a failing `onCancel` callback currently throws its own error:

https://github.com/sindresorhus/p-cancelable/blob/8746e2a93a925e4e28a7848b6e08cad799f33ddd/index.js#L77-L89

And if said `onCancel` callback is called after, it will no longer change the error.

**Comment by jonschlinkert** [comment]
I think the following example demonstrates the same issue (please correct me if I'm wrong): 

```js
const promise = new pCancelable((resolve, reject, onCancel) => {
  const timeout = setTimeout(() => {
    resolve(true);
  }, 1000);

  onCancel.shouldReject(true);
  onCancel(() => {
    clearTimeout(timeout);
    resolve(false);
  });
});

promise.shouldReject = true;
promise.cancel();
promise
  .then(value => console.log(value))
  .catch(console.error);
```

Essentially, since `resolve()` is called inside the `onCancel()` function, the cancellation never occurs, despite `.cancel()` being called before the promise actually resolving. 

I think we can fix this by changing the following code:

https://github.com/sindresorhus/p-cancelable/blob/9fa975b86578b46c1d337dd533addc17fd398187/index.js#L44-L50

To something like this:

```js
const onCancel = handler => {
  if (!this._isPending) {
    throw new Error('The `onCancel` handler was attached after the promise settled.');
  }

  const fn = (...args) => {
    this._isCanceled = true;
    handler(...args);
  };

  this._cancelHandlers.push(fn);
};
```

And we would change the following:

https://github.com/sindresorhus/p-cancelable/blob/9fa975b86578b46c1d337dd533addc17fd398187/index.js#L34-L37

To something like:

```js
const onResolve = value => {
  if (!this._isCanceled) {
    this._isPending = false;
    resolve(value);
  }
};
```

If this seems like an acceptable approach and it solves the problem being described, I'd be happy to do a PR.

**Comment by sindresorhus** [comment]
@jonschlinkert Sounds good. PR welcome 👍
