### ISSUE TITLE
About `AbortController`

### ISSUE THREAD

**Issue by jonschlinkert** [sindresorhus/p-cancelable#27]
The readme says the following:

![image](https://user-images.githubusercontent.com/383994/110231868-5ba53c00-7ee8-11eb-8d3b-2bed15675977.png)

However, the `AbortController` interface is primarily targeted at web requests, and since `p-cancelable` is useful for a lot more than web requests, it might be worth clarifying that in the readme.

**Comment by sindresorhus** [comment]
> However, the AbortController interface is primarily targeted at web requests, and since p-cancelable is useful for a lot more than web requests, it might be worth clarifying that in the readme.

That is not entirely correct. Node.js is adding it to a lot of APIs. The `stream`, `child_process`, and `fs` module supports it now. Yes, `AbortController` started as a way to cancel web requests in the browser, since the standard committees could never decide how to add cancellation to promises. However, since there's no better alternative, a lot of projects are adopting it for everything.

**Comment by jonschlinkert** [comment]
TIL:

> Node.js is adding it to a lot of APIs. The stream, child_process, and fs module supports it now

Nice, I wasn't aware of that! I have some reading to do. 

This just proves [Cunningham's Law](https://www.urbandictionary.com/define.php?term=Cunningham%27s%20law) is correct, once again. 

Closing, thanks!
